### ISSUE TITLE
punctuation mark does not color text

### ISSUE THREAD

**Issue by xOnlyFadi** [kejonaMC/CrossplatForms#175]
### Describe the bug

I have a pinger place holder and when I use in the description it does not color the text because the pinger provides the color with the punctuation mark by itself which cannot be colored is possible to add a fixer it for to make it compatible?

![image](https://github.com/kejonaMC/CrossplatForms/assets/63213308/2feb1d83-bf8a-40b3-ac0a-e58843a73996)

### To Reproduce

use the pinger placeholder online server check

### Expected behaviour

should be coloring the description

### Geyser Dump

https://dump.geysermc.org/06qsepNMmG4qPlgGO7DNz5BhJoKKWpDb

### CrossplatForms Version

1.5.0

**Comment by Konicai** [comment]
This just sounds like an effect of the changes of https://github.com/PlaceholderAPI/PlaceholderAPI/releases/tag/2.11.2 that Pinger must take into account

and Pinger hasn't been updated in 2 years: https://github.com/PlaceholderAPI/Pinger-Expansion/blob/master/src/main/java/com/extendedclip/papi/expansion/pinger/PingerExpansion.java#L23

I don't want to add support for issues caused by outdated expansions/plugins that should be fixed on their end

**Comment by xOnlyFadi** [comment]
> This just sounds like an effect of the changes of https://github.com/PlaceholderAPI/PlaceholderAPI/releases/tag/2.11.2 that Pinger must take into account
> 
> and Pinger hasn't been updated in 2 years: https://github.com/PlaceholderAPI/Pinger-Expansion/blob/master/src/main/java/com/extendedclip/papi/expansion/pinger/PingerExpansion.java#L23
> 
> I don't want to add support for issues caused by outdated expansions/plugins that should be fixed on their end

so probably the best thing is build pinger with the old minecraft symbol?

**Comment by Konicai** [comment]
`§` is the actual standard for the legacy format

**Comment by xOnlyFadi** [comment]
thanks for the help
