### ISSUE TITLE
Convert configs from GeyserHub

### ISSUE THREAD

**Issue by Konicai** [kejonaMC/CrossplatForms#77]
### What feature do you want to see added?

Automatically convert configs from GeyserHub or a command to convert the file.

If anyone is interested in attempting this you'll need to learn or know how to use Configurate's Transformations (see [1](https://github.com/SpongePowered/Configurate/wiki/Transformations-and-Visitors) and [2](https://github.com/SpongePowered/Configurate/blob/master/examples/src/main/java/org/spongepowered/configurate/examples/Transformations.java)). And everything that GeyserHub and CrossplatForms has in common will have to be translated. Start with [MenuConfig](https://github.com/ProjectG-Plugins/CrossplatForms/blob/main/core/src/main/java/dev/projectg/crossplatforms/interfacing/java/MenuConfig.java) and [FormConfig](https://github.com/ProjectG-Plugins/CrossplatForms/blob/main/core/src/main/java/dev/projectg/crossplatforms/interfacing/bedrock/FormConfig.java) and traverse all the fields.

### Are there any alternatives?

Convert it by hand.

**Comment by Jens-Co** [comment]
We could indeed implement a conversion by putting the old config file from geyserhub into the CrossplatForms folder but I think this will add some unnecessary code into the plugin. GeyserHub isn't that much used and conversion by hand would not require much work either since we did not had that many options there. For simplicity I would not add such logic into CrossplatForms. 

This is just my opinion if someone would create a pr for this feel free to do so :)

**Comment by Jens-Co** [comment]
> We could indeed implement a conversion by putting the old config file from geyserhub into the CrossplatForms folder but I think this will add some unnecessary code into the plugin. GeyserHub isn't that much used and conversion by hand would not require much work either since we did not had that many options there. For simplicity I would not add such logic into CrossplatForms.
> 
> This is just my opinion if someone would create a pr for this feel free to do so :)

On a side note we should be archiving GeyserHub anyway.

**Comment by Konicai** [comment]
Implemented in [1.3.1](https://github.com/kejonaMC/CrossplatForms/releases/tag/1.3.1)
